name: Build and Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/molodostclub/molodost-backend:latest

      - name: Deploy to molodost-admin server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_ADMIN_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            echo "Creating persistent directories if not exist"
            mkdir -p /srv/molodost-admin/public/uploads
            mkdir -p /srv/db

            echo "Pulling new backend image"
            docker pull ghcr.io/molodostclub/molodost-backend:latest

            echo "Removing existing service to reapply updated mounts"
            docker service rm molodost_admin || true

            echo "Recreating backend service with correct volume mounts"
            docker service create \
              --name molodost_admin \
              --network molodost_stacknet \
              --network traefiknet \
              --label com.docker.stack.namespace=molodost \
              --label com.docker.stack.image=ghcr.io/molodostclub/molodost-backend \
              --label traefik.enable=true \
              --label traefik.docker.network=traefiknet \
              --label traefik.frontend.rule=Host:molodost-admin.germangorodnev.com,admin.molodost.club \
              --label traefik.port=1337 \
              --mount type=bind,src=/srv/molodost-admin/public/uploads,dst=/srv/app/public/uploads \
              --mount type=bind,src=/srv/db,dst=/srv/app/.tmp \
              --env NODE_ENV=production \
              --env DATABASE_CLIENT=sqlite \
              --env DATABASE_FILENAME=.tmp/data.db \
              --env ADMIN_JWT_SECRET=${{ secrets.ADMIN_JWT_SECRET }} \
              --env API_TOKEN_SALT=${{ secrets.API_TOKEN_SALT }} \
              --env APP_KEYS=${{ secrets.APP_KEYS }} \
              --env JWT_SECRET=${{ secrets.JWT_SECRET }} \
              --env TRANSFER_TOKEN_SALT=${{ secrets.TRANSFER_TOKEN_SALT }} \
              --with-registry-auth \
              ghcr.io/molodostclub/molodost-backend:latest
