name: Build and Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/molodostclub/molodost-backend:latest

      - name: Deploy to molodost-admin server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_ADMIN_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            echo "Pulling latest backend image"
            docker pull ghcr.io/molodostclub/molodost-backend:latest

            echo "Force updating backend service with mounted DB and secrets"
            docker service update molodost_admin \
              --image ghcr.io/molodostclub/molodost-backend:latest \
              --env-add APP_KEYS=${{ secrets.APP_KEYS }} \
              --env-add API_TOKEN_SALT=${{ secrets.API_TOKEN_SALT }} \
              --env-add ADMIN_JWT_SECRET=${{ secrets.ADMIN_JWT_SECRET }} \
              --env-add JWT_SECRET=${{ secrets.JWT_SECRET }} \
              --env-add TRANSFER_TOKEN_SALT=${{ secrets.TRANSFER_TOKEN_SALT }} \
              --mount-rm /srv/app/.tmp/data.db \
              --mount-add type=bind,src=/srv/db,dst=/srv/app/.tmp \
              --mount-add type=bind,src=/srv/molodost-admin/public/uploads,dst=/srv/app/public/uploads \
              --with-registry-auth \
              --force
