name: Build and deploy
on:
  push:
    branches: ['main']

jobs:
  build_docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build production image
        uses: docker/build-push-action@v4.0.0
        with:
          push: true
          context: .
          file: Dockerfile.prod
          tags: ghcr.io/germangorodnev/molodost-admin:latest,ghcr.io/germangorodnev/molodost-admin:${{ github.sha }}
  deploy:
    runs-on: ubuntu-latest
    needs:
      - build_docker
    permissions:
      contents: read
      packages: write
    steps:
      - name: Create SSH key
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.PRIVATE_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.KNOWN_HOST }}" > ~/.ssh/known_hosts
      - name: Update service
        run: ssh -o "StrictHostKeyChecking=no" circleci@${{ secrets.SWARM_MANAGER }} docker service update molodost_admin --image ghcr.io/germangorodnev/molodost-admin:${{ github.sha }} --with-registry-auth
